name: Validate PR
on:
  pull_request:
  merge_group:
jobs:
  static_checks:
    name: validate-changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check files changed
        run: |
          echo "=======CHECKOUT REMOTE BRANCH ========"
          git remote add upstream https://github.com/susdas-qe/test-merge-queue.git
          echo "========= FETCHING REMOTE BRANCHES"
          git fetch upstream
          echo "==========CURRENT BRANCH======="
          git rev-parse --abbrev-ref HEAD
          echo "====== SHA THAT TRIGGERS THE WORKFLOW: ${{ github.sha }}"
          echo "==========CHANGED FILES======="
          git diff --name-status "upstream/main..HEAD"