name: Validate PR
on:
  pull_request:
jobs:
  static_checks:
    name: validate-changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check files changed
        run: |
          git remote -v