name: Validate PR
on:
  pull_request:
  merge_group:
jobs:
  static_checks:
    name: validate-changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Differential Checkton requires full git history
          fetch-depth: 0

      - name: check values
        run: |
          echo "GITHUB REF: ${GITHUB_REF}"
          echo "SHA: ${GITHUB_SHA}"
          echo "BASE: $(git rev-parse main)"
          echo "HEAD: $(git rev-parse HEAD)"

      - name: Run Checkton
        id: checkton
        uses: chmeliik/checkton@v0.3.1
        with:
          # Set to false when re-enabling SARIF uploads
          fail-on-findings: true
          find-copies-harder: true
          exclude-regex: ^task-generator

      # - uses: actions/checkout@v4
      #   with:
      #     ref: "${{ github.event.pull_request.head.sha }}"
      #     path: test-merge-queue
      # - name: Get all changed files in the PR from task directory
      #   id: changed-dirs
      #   uses: tj-actions/changed-files@27ae6b33eaed7bf87272fdeb9f1c54f9facc9d99
      #   with:
      #     path: test-merge-queue
      # - name: Print all the changed_files
      #   run: |
      #     echo "${{ steps.changed-dirs.outputs.all_changed_files }}"
      # - name: check files changed
      #   run: |
      #     echo "=======CHECKOUT REMOTE BRANCH ========"
      #     git remote add upstream https://github.com/susdas-qe/test-merge-queue.git
      #     echo "========= FETCHING REMOTE MAIN BRANCH"
      #     git fetch upstream main
      #     echo "==========CURRENT BRANCH======="
      #     git rev-parse --abbrev-ref HEAD
      #     echo "====== SHA THAT TRIGGERS THE WORKFLOW: ${{ github.sha }}"
      #     changed_files=$(git diff --name-only "upstream/main..HEAD" | tr "\n" " ")
      #     echo "CHANED FILES: ${changed_files}"
      #     ./sample.py ${changed_files}